# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import weather_pb2 as weather__pb2


class WeatherStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CurrentConditions = channel.unary_unary(
        '/weather.Weather/CurrentConditions',
        request_serializer=weather__pb2.WeatherRequest.SerializeToString,
        response_deserializer=weather__pb2.WeatherResponse.FromString,
        )


class WeatherServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CurrentConditions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WeatherServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CurrentConditions': grpc.unary_unary_rpc_method_handler(
          servicer.CurrentConditions,
          request_deserializer=weather__pb2.WeatherRequest.FromString,
          response_serializer=weather__pb2.WeatherResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'weather.Weather', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
