---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: weather-api
    name: weather-api
  spec:
    ports:
    - name: http-api
      port: 8000
      targetPort: 5000
    selector:
      app: weather-api
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: weather-api-v2
    labels:
      app: weather-api
      tier: api
      version: v1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: weather-api
        version: v1
    template:
      metadata:
        labels:
          app: weather-api
          tier: api
          version: v1
      spec:
        containers:
        - image: andrewb3000/grpc-weather-api:1
          imagePullPolicy: IfNotPresent
          name: grpc-weather-api
          env:
          - name: WEATHER_SERVICE_URL
            value: weather-be:9000
          - name: WEATHER_LOCATION
            value: 'London, UK'
          ports:
            - containerPort: 5000
