# ---
#   apiVersion: v1
#   kind: Service
#   metadata:
#     labels:
#       app: weather-api
#     name: weather-api
#   spec:
#     ports:
#     - name: http-api
#       port: 80
#       targetPort: 5000
#     selector:
#       app: weather-api
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: weather-api-v2a
    labels:
      app: weather-api
      tier: api
      version: v2alpha
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: weather-api
        version: v2alpha
    template:
      metadata:
        labels:
          app: weather-api
          tier: api
          version: v2alpha
      spec:
        containers:
        - image: andrewb3000/grpc-weather-api:2
          imagePullPolicy: IfNotPresent
          name: grpc-weather-api
          env:
          - name: WEATHER_SERVICE_URL
            value: weather-be:9000
          - name: WEATHER_LOCATION
            value: '["Berlin, Germany"]'
          ports:
            - containerPort: 5000
