---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gweather-be
    name: gweather-be
  spec:
    ports:
    - name: grpc-be
      port: 9000
    selector:
      app: gweather-be
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: gweather-be
    labels:
      app: geather-be
      tier: backend
      version: v1
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: gweather-be
        version: v1
    template:
      metadata:
        labels:
          app: gweather-be
          tier: backend
          version: v1
      spec:
        containers:
        - image: caiofilipini/grpc-weather:master
          imagePullPolicy: IfNotPresent
          name: grpc-weather
          env:
          - name: OPEN_WEATHER_MAP_API_KEY
            value: a998bb724d70364542952d297b951cdf
          - name: WEATHER_UNDERGROUND_API_KEY
            value: 0dd5caf56d01bb7b
          ports:
            - containerPort: 9000
