---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: weather-ui
    name: weather-ui
  spec:
    ports:
    - name: http-ui
      port: 80
      targetPort: 5000
    selector:
      app: weather-ui
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: weather-ui
    labels:
      app: weather-ui
      tier: ui
      version: v1
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: weather-ui
        version: v1
    template:
      metadata:
        labels:
          app: weather-ui
          tier: ui
          version: v1
      spec:
        containers:
        - image: andrewb3000/getsomeurl:3
          imagePullPolicy: IfNotPresent
          name: getsomeurl
          env:
          - name: REQUEST_URL
            value: http://weather-api/getweather
          ports:
            - containerPort: 5000
