# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='weather',
  syntax='proto3',
  serialized_pb=_b('\n\rweather.proto\x12\x07weather\"\"\n\x0eWeatherRequest\x12\x10\n\x08location\x18\x01 \x01(\t\"J\n\x0fWeatherResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05\x66ound\x18\x03 \x01(\x08\x32S\n\x07Weather\x12H\n\x11\x43urrentConditions\x12\x17.weather.WeatherRequest\x1a\x18.weather.WeatherResponse\"\x00\x62\x06proto3')
)




_WEATHERREQUEST = _descriptor.Descriptor(
  name='WeatherRequest',
  full_name='weather.WeatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='weather.WeatherRequest.location', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=60,
)


_WEATHERRESPONSE = _descriptor.Descriptor(
  name='WeatherResponse',
  full_name='weather.WeatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='weather.WeatherResponse.temperature', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='weather.WeatherResponse.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='found', full_name='weather.WeatherResponse.found', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['WeatherRequest'] = _WEATHERREQUEST
DESCRIPTOR.message_types_by_name['WeatherResponse'] = _WEATHERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeatherRequest = _reflection.GeneratedProtocolMessageType('WeatherRequest', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERREQUEST,
  __module__ = 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.WeatherRequest)
  ))
_sym_db.RegisterMessage(WeatherRequest)

WeatherResponse = _reflection.GeneratedProtocolMessageType('WeatherResponse', (_message.Message,), dict(
  DESCRIPTOR = _WEATHERRESPONSE,
  __module__ = 'weather_pb2'
  # @@protoc_insertion_point(class_scope:weather.WeatherResponse)
  ))
_sym_db.RegisterMessage(WeatherResponse)



_WEATHER = _descriptor.ServiceDescriptor(
  name='Weather',
  full_name='weather.Weather',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=138,
  serialized_end=221,
  methods=[
  _descriptor.MethodDescriptor(
    name='CurrentConditions',
    full_name='weather.Weather.CurrentConditions',
    index=0,
    containing_service=None,
    input_type=_WEATHERREQUEST,
    output_type=_WEATHERRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHER)

DESCRIPTOR.services_by_name['Weather'] = _WEATHER

# @@protoc_insertion_point(module_scope)
