apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: service-egress-viewer
  # namespace: weather
spec:
  rules:
  - services: ["istio-egressgateway.istio-system.svc.cluster.local"]
    methods: ["*"]
    # paths:
    # - ".*"
    # constraints:
    # - key: "app"
    #   values: [weather-be"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-service-egress-viewer
  # namespace: weather
spec:
  subjects:
  ## Allow requests within weather namespace
  - properties:
      namespace: "weather"
  ## Allow requests from Istio ingressgateway
  - properties:
      namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-egress-viewer"
