apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: weather-getter
  namespace: weather
spec:
  rules:
  - services: ["*"]
    #methods: ["GET", "weather.Weather/POST", "weather.Weather/CurrentConditions", "Weather.CurrentConditions/POST", "POST"]
    methods: ["GET"]
    # paths:
    # - ".*"
    #constraints:
    # - key: "app"
    #   values: ["weather-ui", "weather-api"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: ingress2weather-weather2weather
  namespace: weather
spec:
  subjects:
  ## Allow requests within weather namespace
  - properties:
      namespace: "weather"
  ## Allow requests from Istio ingressgateway
  - properties:
      namespace: "istio-system"
#      istio: "ingressgateway"
  roleRef:
    kind: ServiceRole
    name: "weather-getter"
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: backend-poster
  namespace: weather
spec:
  rules:
  - services: ["weather-be.weather.svc.cluster.local"]
    methods: ["POST"]
    paths:
    - "/weather.Weather/CurrentConditions"
    # constraints:
    # - key: "app"
    #   values: ["weather-ui", "weather-api"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: api2backend-poster
  namespace: weather
spec:
  subjects:
  - properties:
      app: "weather-api"
  roleRef:
    kind: ServiceRole
    name: "backend-poster"
