apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: egress-service-viewer
  namespace: istio-system
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-egress-service-viewer
  namespace: istio-system
spec:
  subjects:
  ## Allow requests within weather namespace
  - properties:
      namespace: "weather"
  ## Allow requests from Istio ingressgateway
  - properties:
      namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"
