apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: service-ingress
  namespace: weather
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    # paths:
    # - "/somepath"
    # constraints:
    # - key: "app"
    #   values: ["weather-ui"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-service-ingress
  namespace: weather
spec:
  subjects:
  ## Allow requests from Istio ingressgateway
  - properties:
      namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-ingress"
