apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: service-ui
  namespace: weather
spec:
  rules:
  - services: ["weather-api"]
    # methods: ["GET", "weather.Weather/POST", "weather.Weather/CurrentConditions", "Weather.CurrentConditions/POST", "POST"]
    methods: ["GET"]
    # paths:
    # - ".*"
    # constraints:
    # - key: "app"
    #   values: ["weather-ui", "weather-api"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-service-ui
  namespace: weather
spec:
  subjects:
  ## Allow requests within weather namespace
  - properties:
      service: "weather-ui"
  ## Allow requests from Istio ingressgateway
  # - properties:
  #     namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-ui"
