apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
  name: service-viewer
  namespace: demo
spec:
  rules:
  - services: ["*"]
    methods: ["GET"]
    # paths:
    # - ".*"
    # constraints:
    # - key: "app"
    #   values: ["weather-ui", "weather-api", "weather-be"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: demo
spec:
  subjects:
  ## Allow requests within weather namespace
  - properties:
      namespace: "demo"
  ## Allow requests from Istio ingressgateway
  - properties:
      namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"
